version: "3.7"
services:
  app:
    build:
      args:
        user: kandi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sikepokting
    container_name: sikepokting-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:alpine
    depends_on:
      - app
    container_name: sikepokting-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/